#
##Database details
#
Adapter: ''
Encoding: ''
Pool: ''
Username: ''
RESERVATION_SYSTEM_DATABASE_PASSWORD: ''

#
##Mailer Credentials
#
SMTP_ADDRESS: ''
SMTP_PORT: ''
SMTP_DOMAIN: ''
SMTP_AUTHENTICATION: ''
SMTP_USER_NAME: ''
SMTP_PASSWORD: ''

#
##HOST
#
Host: ''
ASSET_HOST: ''
